services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: firstblueice/ml_2023_spring_env:2.0
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock